@workflow-url=http://localhost:5049
@dapr-url=http://localhost:3504
@shipping-url=http://localhost:5051
@orderId={{$guid}}
@productId=RBD1000

### Restock inventory
POST {{workflow-url}}/inventory/restock
Content-Type: application/json

{
    "productId": "{{productId}}",
    "quantity": 5
}

### Get inventory
GET {{workflow-url}}/inventory/{{productId}}


### Schedule a workflow instance via the .NET application
# @name validateOrderResponse
POST {{workflow-url}}/validateOrder
Content-Type: application/json

{
    "id": "{{orderId}}",
    "orderItem" : {
        "productId": "{{productId}}",
        "productName": "RubberDuck",
        "quantity": 2,
        "totalPrice": 5.00
    },
    "contactInfo" : {
        "country" : "The Netherlands"
    }
}

### GET workflow status directly via the Dapr HTTP API
@instanceId={{validateOrderResponse.response.headers.Location}}
GET {{dapr-url}}/v1.0-beta1/workflows/dapr/{{instanceId}}

### Schedule a workflow instance directly via the Dapr HTTP API
POST {{dapr-url}}/v1.0-beta1/workflows/dapr/ValidateOrderWorkflow/start?instanceID={{orderId}}
Content-Type: application/json

{
    "id": "{{orderId}}",
    "orderItem" : {
        "productId": "{{productId}}",
        "productName": "RubberDuck",
        "quantity": 1,
        "totalPrice": 5.00
    },
    "shippingInfo" : {
        "country" : "The Netherlands"
    }
}

### Calculate shipping cost

POST {{shipping-url}}/calculateCost
Content-Type: application/json

{
    "country": "The Netherlands"
}