dapr uninstall
dapr init
dotnet build ResiliencyDemo/ValidationService/ValidationService.csproj
dotnet build ResiliencyDemo/ProfileService/ProfileService.csproj
dotnet build WorkflowDemo/ShippingApp/ShippingApp.csproj
dotnet build WorkflowDemo/WorkflowApp/WorkflowApp.csproj