@app-a-url=http://localhost:5045
@app-b-url=http://localhost:5047

### POST SocialProfileDetails
POST {{app-a-url}}/post
Content-Type: application/json

{
    "name": "Marc",
    "twitterHandle": "marcduiker",
    "githubHandle": "marcduiker"
}

### GET SocialProfileDetails
GET {{app-b-url}}/profile/marcduiker

### POST SocialProfileDetails via pubsub
POST {{app-a-url}}/pubsub
Content-Type: application/json

{
    "name": "Marc",
    "twitterHandle": "marcduiker",
    "githubHandle": "marcduiker"
}